# Generated by Django 3.0 on 2022-02-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.CharField(max_length=200, verbose_name='Top Text')),
                ('bottom', models.CharField(max_length=200, verbose_name='Bottom Text')),
                ('is_active', models.BooleanField(default=True, verbose_name='In Slider?')),
            ],
        ),
    ]
