# Generated by Django 3.0 on 2022-02-15 22:11

import bboard.utilities
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namee', models.CharField(max_length=20, verbose_name='Category')),
                ('order', models.SmallIntegerField(db_index=True, default=0, verbose_name='Number')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ['is_active'], 'verbose_name': 'slider', 'verbose_name_plural': 'Sliders'},
        ),
        migrations.AlterField(
            model_name='hero',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='In Slider?'),
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_work', models.CharField(max_length=20, verbose_name='Name')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='In work?')),
                ('image', models.ImageField(upload_to=bboard.utilities.get_timestamp_path, verbose_name='Image')),
                ('cetegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.Category')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
                'ordering': ['is_active'],
            },
        ),
    ]
