# Generated by Django 3.0 on 2022-02-15 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20220215_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
    ]
