# Generated by Django 3.0 on 2022-02-15 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_auto_20220215_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
