# Generated by Django 3.0 on 2022-02-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_descriptionour_ouravesome'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptionour',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='In work?'),
        ),
    ]
