# Generated by Django 3.0 on 2022-02-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_auto_20220216_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=30, verbose_name='Category')),
                ('text2', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'Our Proc',
                'verbose_name_plural': 'Our Proc',
            },
        ),
        migrations.CreateModel(
            name='WhoAreWe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_are', models.CharField(max_length=30, verbose_name='Table of contents')),
                ('description_who', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Who are We',
                'verbose_name_plural': 'Who are We',
            },
        ),
        migrations.AlterModelOptions(
            name='descriptionour',
            options={'ordering': ['is_active'], 'verbose_name': 'Our Description', 'verbose_name_plural': 'Our Description'},
        ),
    ]
