# Generated by Django 3.0 on 2022-02-17 17:45

import bboard.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_auto_20220216_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('position', models.CharField(max_length=20, verbose_name='Position')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('facebook', models.CharField(max_length=20, verbose_name='Facebook')),
                ('twitter', models.CharField(max_length=20, verbose_name='Twitter')),
                ('skype', models.CharField(max_length=20, verbose_name='Skype')),
                ('gmail', models.EmailField(max_length=60, verbose_name='Gmail')),
                ('image', models.ImageField(upload_to=bboard.utilities.get_timestamp_path, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'OurTeam',
                'verbose_name_plural': 'OurTeam',
            },
        ),
    ]
