# Generated by Django 3.0 on 2022-02-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0009_ourteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='facebook',
            field=models.CharField(max_length=60, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='skype',
            field=models.CharField(max_length=60, verbose_name='Skype'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='twitter',
            field=models.CharField(max_length=60, verbose_name='Twitter'),
        ),
    ]
