# Generated by Django 3.0 on 2022-02-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0010_auto_20220217_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='gmail',
            field=models.EmailField(max_length=60, unique=True, verbose_name='Gmail'),
        ),
    ]
