# Generated by Django 3.0 on 2022-02-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0012_auto_20220217_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='In work?'),
        ),
    ]
