# Generated by Django 3.0 on 2022-02-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0013_ourteam_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60, verbose_name='Text')),
                ('description', models.TextField(verbose_name='Desc')),
                ('is_active', models.BooleanField(default=False, verbose_name='In Page?')),
                ('button', models.CharField(blank=True, max_length=40, verbose_name='Text on button')),
            ],
            options={
                'verbose_name': 'Button and Text',
                'verbose_name_plural': 'Button and Text',
                'ordering': ['is_active'],
            },
        ),
    ]
