# Generated by Django 3.0 on 2022-02-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0015_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='In feedback?'),
        ),
    ]
