# Generated by Django 3.0 on 2022-02-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0016_feedback_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetInTuch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(max_length=50, verbose_name='Name')),
                ('contactEmail', models.EmailField(max_length=254, verbose_name='Email')),
                ('contactSubject', models.CharField(max_length=60, verbose_name='Subject')),
                ('contactMessage', models.TextField(verbose_name='Message')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': '1Customer',
                'verbose_name_plural': '1Customers',
                'ordering': ['date'],
            },
        ),
    ]
