# Generated by Django 3.0 on 2022-02-18 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0017_getintuch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Text')),
                ('adress', models.CharField(max_length=80, verbose_name='Address')),
                ('phoneNumber', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Phone Number')),
                ('facebook', models.CharField(max_length=40, verbose_name='Facebook')),
                ('twitter', models.CharField(max_length=40, verbose_name='Twitter')),
                ('youtube', models.CharField(max_length=40, verbose_name='YouTube')),
                ('vimeo', models.CharField(max_length=40, verbose_name='Vimeo')),
                ('flick', models.CharField(max_length=40, verbose_name='Flick')),
                ('skype', models.CharField(max_length=40, verbose_name='Skype')),
                ('num', models.SmallIntegerField(verbose_name='Number')),
            ],
            options={
                'verbose_name': 'Company Data',
                'verbose_name_plural': 'Company Data',
            },
        ),
    ]
