# Generated by Django 3.0 on 2022-02-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0018_companydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='flick',
            field=models.CharField(max_length=40, verbose_name='Flickr'),
        ),
    ]
